services:
  pg:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.0
    ports:
      - "6379:6379"