### Get all indices
GET http://localhost:9200/_cat/indices?v

### Create index
# PUT /events-001
PUT http://localhost:9200/events-001
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 3,
    "number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "id": { "type": "keyword" },
      "name": { "type": "text" },
      "venue": {
        "properties": {
          "id": { "type": "keyword" },
          "name": { "type": "text" },
          "city": { "type": "text" },
          "state": { "type": "keyword" },
          "country": { "type": "keyword" }
        }
      },
      "event_date": { "type": "date" }
    }
  }
}

### Alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
  "actions": [
    {
      "add": {
        "index": "events-001",
        "alias": "events"
      }
    }
  ]
}

### Search query
GET http://localhost:9200/events/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "query": "concerts e stadiums",
            "fields": ["name", "venue.name"]
          }
        }
      ],
      "filter": [
        {
          "range": {
            "event_date": {
              "gte": "2024-12-01",
              "lte": "2024-12-31"
            }
          }
        },
        {
          "term": {
            "venue.country": "USA"
          }
        }
      ]
    }
  }
}


### Search through API
curl -X GET "http://localhost:8080/search" -d '{
  "query": "Concert",
  "date_from": "2024-12-01",
  "date_to": "2024-12-31"
}'

### Create a New Index with Updated Mappings
### Update `city` field type from `text` to `keyword`
PUT http://localhost:9200/events-002
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 3,
    "number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "id": { "type": "keyword" },
      "name": { "type": "text" },
      "venue": {
        "properties": {
          "id": { "type": "keyword" },
          "name": { "type": "text" },
          "city": { "type": "keyword" },
          "state": { "type": "keyword" },
          "country": { "type": "keyword" }
        }
      },
      "event_date": { "type": "date" }
    }
  }
}


### Reindex Data from Old Index to New Index
POST http://localhost:9200/_reindex
Content-Type: application/json

{
  "source": {
    "index": "events-001"
  },
  "dest": {
    "index": "events-002"
  }
}

### Alias
POST http://localhost:9200/_aliases
Content-Type: application/json

{
  "actions": [
    { "remove": { "index": "events-001", "alias": "events" } },
    { "add": { "index": "events-002", "alias": "events" } }
  ]
}

### Delete Old Index
DELETE http://localhost:9200/events-001